service: reto-tecnico-api

# Create an optimized package for our functions 
package:
  individually: true
  exclude:
    - node_modules/**
    - src/**
    - tests/**

plugins:
  - serverless-offline
  - serverless-dotenv-plugin # Load .env as environment variables

provider:
  name: aws
  runtime: nodejs10.x
  stage: dev
  region: us-east-1

  environment:
    SAMPLE_ENV_VAR: ${env:SAMPLE_ENV_VAR}

  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:DescribeStream
        - dynamodb:GetRecords
        - dynamodb:GetShardIterator
        - dynamodb:ListStreams
      Resource:
        Fn::GetAtt: [NotesTable, StreamArn]

functions:
  testDynamoTrigger:
    handler: src/handler.testDynamoTrigger
    events:
      - http:
          path: /hello
          method: get
      - stream:
          type: dynamodb
          arn:
            Fn::GetAtt: [NotesTable, StreamArn]
    package:
      include:
        - src/handler.js

resources:
  Resources:
    NotesTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: notes
        AttributeDefinitions:
          - AttributeName: userId
            AttributeType: S
          - AttributeName: noteId
            AttributeType: S
        KeySchema:
          - AttributeName: userId
            KeyType: HASH
          - AttributeName: noteId
            KeyType: RANGE
        BillingMode: PAY_PER_REQUEST
        StreamSpecification:
          StreamViewType: NEW_AND_OLD_IMAGES